name: Check Server Status

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows you to click "Run Now" button manually

permissions:
  contents: write

jobs:
  check-port:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Port 22 (SSH)
        id: check
        run: |
          # Use netcat (nc) to scan the IP and Port with a 5 second timeout
          if nc -z -v -w 5 77.93.155.98 22; then
            echo "STATUS=online" >> $GITHUB_ENV
            echo "Server is UP"
          else
            echo "STATUS=offline" >> $GITHUB_ENV
            echo "Server is DOWN"
          fi

      - name: Generate JSON Report
        run: |
          # Create a JSON file with the current status and time
          echo "{ \"status\": \"$STATUS\", \"last_check\": \"$(date -u)\" }" > status.json

      - name: Commit and Push
        run: |
          git config --global user.name 'Server Monitor Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add status.json
          # Only commit if the status has changed or to update timestamp
          git commit -m "Update server status to $STATUS" || exit 0
          git push
